// src/products.js
export const products = [
  {
    id: 1,
    name: "Nike Run Defy",
    price: 12000,
    description: "Comfortable and stylish shoes for daily wear.",
    images: ["/shoes1.jpg", "/shoes1-1.jpg", "/shoes1-2.jpg", "/shoes1-3.jpg"],
  },
  {
    id: 2,
    name: "Nike Zoom Rival Fly 4",
    price: 12000,
    description: "High-performance running shoes with modern design.",
    images: ["/shoes2.jpg", "/shoes2-1.jpg", "/shoes2-2.jpg", "/shoes2-3.jpg"],
  },
  {
    id: 3,
    name: "Nike Run Swift 3",
    price: 14000,
    description: "Premium quality UB 5 shoes for running and training.",
    images: ["/shoes11.jpg", "/shoes11.1.jpg","/shoes11.2.jpg", "/shoes11.3.jpg"],
  },
  {
    id: 4,
    name: "Nike Vomero 18 GORE-TEX",
    price: 16000,
    description: "Lightweight and responsive shoes for speed runners.",
    images: ["/shoes12.jpg", "/shoes12-1.jpg","/shoes12-2.jpg", "/shoes12-3.jpg"],
  },
  {
    id: 5,
    name: "Nike Ultrafly",
    price: 15000,
    description: "Elite racing shoes with carbon plate technology.",
    images: ["/shoes13.jpg", "/shoes13-1.jpg","/shoes13.2.jpg","/shoes13-3.jpg"],
  },
  {
    id: 6,
    name: "Nike Vomero Premium",
    price: 13000,
    description: "Breathable and stylish white running shoes.",
    images: ["/shoes14.jpg", "/shoes14-1.jpg","/shoes14-2.jpg","/shoes14.3.jpg"],
  },
  {
    id: 7,
    name: "Nike Vomero 18",
    price: 13000,
    description: "Durable winter tech shoes with excellent grip.",
    images: ["/shoes15.jpg", "/shoes15-1.jpg","/shoes15-2.jpg", "/shoes15-3.jpg"],
  },
  {
    id: 8,
    name: "Nike Motiva",
    price: 19000,
    description: "New Balance Fresh Foam X with premium comfort.",
    images: ["/shoes16.jpg", "/shoes16-1.jpg","/shoes16-2.jpg","/shoes16-3.jpg"],
  },
  {
    id: 9,
    name: "Nike Pegasus 41",
    price: 10000,
    description: "Classic AM 720 shoes with cushioned support.",
    images: ["/shoes17.jpg", "/shoes17-1.jpg","/shoes17-2.jpg","/shoes17-3.jpg",],
  },
  {
    id: 10,
    name: "Nike Zoom Rival Sprint",
    price: 15000,
    description: "Stylish all-black design with Fresh Foam comfort.",
    images: ["/shoes18.jpg", "/shoes18-1.jpg","/shoes18-2.jpg","/shoes18-3.jpg"],
  },
  {
    id: 11,
    name: "Nike Run Defy",
    price: 12000,
    description: "Premium Dunk Low sneakers with venom theme.",
    images: ["/shoes19.jpg", "/shoes19-1.jpg","/shoes19-2.jpg","/shoes19-3.jpg"],
  },
  {
    id: 12,
    name: "Nike Vomero Plus",
    price: 12000,
    description: "Air Jordan IV Fear edition with iconic style.",
    images: ["/shoes20.jpg", "/shoes20-1.jpg","/shoes20-2.jpg","/shoes20-3.jpg",],
  },
];
